[package]
name = "rtltcp"
version = "0.1.0"
authors = ["Niclas Hoyer <niclas@verbugt.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["daemon_systemd"]
daemon_systemd = ["listenfd", "systemd"]

[dependencies]
"rtlsdr_mt" = "*"
"slog" = { version = "*", features = ["max_level_debug", "release_max_level_debug"] }
"slog-async" = "*"
"slog-term" = "*"
"listenfd" = { version = "*", optional = true }
"systemd" = { version = "*", "optional" = true }
"ctrlc" = "*"
